### ISSUE TITLE
Does not work with memory dumps copied from Firefox

### ISSUE THREAD

**Issue by cassiebeckley** [bcoburn3/vmdecode#1]
When copying from the AVR emulator's memory, Chrome seems to copy the spaces between table columns as tabs, whereas Firefox copies them as two spaces.

This causes a problem with the hexdump parser - at the moment, it grabs the characters from column 5 to column 53 (`scanner.Text()[5:53]`), and ignores the rest. This works with Chrome, where the hex content does span from 5 to 53, but not with Firefox, where the extra characters cause the content to span from 5 to 69.

**Comment by bcoburn3** [comment]
Thanks for finding this, I'm glad to know that other people are looking at my code.

I'm on vacation until the 5th, I'll fix this when I get back.
